# Generated by Django 3.2.7 on 2021-09-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('colors', models.JSONField(verbose_name='Colors')),
            ],
            options={
                'db_table': 'Images',
                'ordering': ['upload_date'],
            },
        ),
    ]
