# Generated by Django 3.2.7 on 2021-09-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='colors',
        ),
        migrations.CreateModel(
            name='PixelCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_colors', models.JSONField(verbose_name='Colors')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='backend.images')),
            ],
            options={
                'db_table': 'PixelCounts',
            },
        ),
    ]
