# Generated by Django 3.2.7 on 2021-09-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210910_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='PixelCounts',
            new_name='PixelCount',
        ),
    ]
